# Introducción a NumPy

[Numpy](https://numpy.org) es una librería fundamental para la computación científica con Python.
* Proporciona arrays N-dimensionales
* Implementa funciones matemáticas sofisticadas
* Proporciona herramientas para integrar C/C++ y Fortran
* Proporciona mecanismos para facilitar la realización de tareas relacionadas con álgebra lineal o números aleatorios

## Imports

In [23]:
import numpy as np


FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'c:\\Program Files\\Python310\\lib\\matplotlib.libs'

## Arrays

Un **array** es una estructura de datos que consiste en una colección de elementos (valores o variables), cada uno identificado por al menos un índice o clave. Un array se almacena de modo que la posición de cada elemento se pueda calcular a partir de su tupla de índice mediante una fórmula matemática. El tipo más simple de array es un array lineal, también llamado array unidimensional.

En numpy:
* Cada dimensión se denomina **axis**
* El número de dimensiones se denomina **rank**
* La lista de dimensiones con su correspondiente longitud se denomina **shape**
* El número total de elementos (multiplicación de la longitud de las dimensiones) se denomina **size**

In [5]:
#Array cuyos valores son 0
a = np.zeros((2,4))


In [6]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

_**a**_ es un array:
* Con dos **axis**, el primero de longitud 2 y el segundo de longitud 4
* Con un **rank** igual a 2
* Con un **shape** igual (2, 4)
* Con un **size** igual a 8

In [7]:
a.shape

(2, 4)

In [8]:
a.ndim

2

In [9]:
a.size

8

## Creación de Arrays

In [10]:
# Array cuyos valores son todos 0
np.zeros((2,3,4))


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
# Array cuyos valores son todos 1
np.ones((2,3,4))


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [12]:
# Array cuyos valores son todos el valor indicado como segundo parámetro de la función
np.full((2,3,4),8)


array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [13]:
# El resultado de np.empty no es predecible 
# Inicializa los valores del array con lo que haya en memoria en ese momento

np.empty((2,3,9))


array([[[ 9.88131292e-323,  1.13203778e-311,  6.77023370e+223,
          1.13204769e-311,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000, -3.80409446e-311,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000,  0.00000000e+000]],

       [[-7.60671225e-311,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
          0.00000000e+000,  0.00000000e+000,  1.13204769e-311],
        [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         -4.34732691e-311,  0.00000000e+000, -8.19450524e-311,
          1.13204769e-311,  1.13204769e-311,  6.79834329e-321],
        [ 9.88131292e-324,  1.13204769e-311,  1.

In [14]:
# Inicializacion del array utilizando una lista de Python

b = np.array(([1,2,3],[4,5,6]))
b


array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b.shape

(2, 3)

In [16]:
# Creación del array utilizando una función basada en rangos
# (minimo, maximo, número elementos del array)
print(np.linspace(0,6,10))


[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]


In [17]:
# Inicialización del array con valores aleatorios

np.random.rand(2,3,4)


array([[[0.84487724, 0.83168031, 0.9107802 , 0.67331795],
        [0.60379844, 0.19433297, 0.9743047 , 0.1141171 ],
        [0.5022328 , 0.39195327, 0.89497619, 0.46852034]],

       [[0.50889691, 0.52443803, 0.16152966, 0.53599636],
        [0.40207501, 0.46858218, 0.38615825, 0.66436685],
        [0.69691798, 0.80128174, 0.58857502, 0.85182253]]])

In [18]:
# Inicialización del array con valores aleatorios conforme a una distribución normal
np.random.randn(2,4)

array([[ 0.05795871,  1.17289282,  0.80581635,  0.25473299],
       [-0.40715778,  0.27273274,  0.88473588, -1.42315198]])

In [21]:


import matplotlib.pyplot as plt
c = np.random.randn(1000000)

plt.hist(c, bins=200)
plt.show()

FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'c:\\Program Files\\Python310\\lib\\matplotlib.libs'

## Acceso a los elementos de un array

### Array unidimensional

In [24]:
# Creación de un Array unidimensional
array_uni = np.array([1,3,5,7,9,11])
print("Shape", array_uni.shape)
print("Array unidimensional", array_uni)

Shape (6,)
Array unidimensional [ 1  3  5  7  9 11]


In [25]:
# Accediendo al quinto elemento del Array
print(array_uni[4])

9


In [26]:
# Accediendo al tercer y cuarto elemento del Array
array_uni[2:4]

array([5, 7])

In [ ]:
# Accediendo a los elementos 0, 3 y 5 del Array


### Array multidimensional

In [28]:
# Creación de un Array multidimensional
array_mult = np.array(([1,2,3,4],[5,6,7,8]))
print("Shape", array_mult.shape)
print("Array multi: ", array_mult)

Shape (2, 4)
Array multi: [[1 2 3 4]
 [5 6 7 8]]


In [29]:
# Accediendo al cuarto elemento del Array

array_mult[0,3]


4

In [30]:
# Accediendo a la segunda fila del Array
array_mult[1,:]

array([5, 6, 7, 8])

In [31]:
# Accediendo al tercer elemento de las dos primeras filas del Array
array_mult[0:2,2]

array([3, 7])

## Modificación de un Array

In [32]:
# Creación de un Array unidimensional inicializado con el rango de elementos 0-27
array1 = np.arange(28)
print("Shape", array1.shape)
print("Arry1", array1)

Shape (28,)
Arry1 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [34]:
# Cambiar las dimensiones del Array y sus longitudes

array1.shape = (7,4)
print("shape",array1.shape)
print("array1", array1)

shape (7, 4)
array1 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


In [36]:
# El ejemplo anterior devuelve un nuevo Array que apunta a los mismos datos. 
# Importante: Modificaciones en un Array, modificaran el otro Array

array2 = array1.reshape(4,7)
print("shape",array2.shape)
print("array2",array2)

shape (4, 7)
array2 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [37]:
# Modificación del nuevo Array devuelto
array2[0,3]= 20 
print("Array 2",array2)

Array 2 [[ 0  1  2 20  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [38]:
# Desenvuelve el Array, devolviendo un nuevo Array de una sola dimension
# Importante: El nuevo array apunta a los mismos datos
print("Array1", array1.ravel())


Array1 [ 0  1  2 20  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


## Operaciones aritméticas con Arrays

In [41]:
# Creación de dos Arrays unidimensionales
array1 = np.arange(2,18,2)
array2 = np.arange(8)

print("Array 1", array1)
print("Array 2", array2)




Array 1 [ 2  4  6  8 10 12 14 16]
Array 2 [0 1 2 3 4 5 6 7]


In [42]:
# Suma

print(array1+array2)

[ 2  5  8 11 14 17 20 23]


In [43]:
# Resta
print(array1 - array2)

[2 3 4 5 6 7 8 9]


In [44]:
# Multiplicacion
# Importante: No es una multiplicación de matrices

print(array1 * array2)

[  0   4  12  24  40  60  84 112]


## Broadcasting

Si se aplican operaciones aritméticas sobre Arrays que no tienen la misma forma (shape) Numpy aplica un propiedad que se denomina Broadcasting.

In [47]:
# Creación de dos Arrays unidimensionales

array1 = np.arange(5)
array2 = np.array([3])
print("Shape array1", array1.shape)
print("Array1", array1)
print()
print("Shape array2", array2.shape)
print("Array2", array2)




Shape array1 (5,)
Array1 [0 1 2 3 4]

Shape array2 (1,)
Array2 [3]


In [48]:
# Suma de ambos Arrays
array1+array2

array([3, 4, 5, 6, 7])

In [56]:
# Creación de dos Arrays multidimensional y unidimensional

array1 = np.arange(6)
array1.shape = (2,3)

array2 = np.arange(6,18,4)
print("Shape array1", array1.shape)
print("Array1", array1)
print()
print("Shape array2", array2.shape)
print("Array2", array2)



Shape array1 (2, 3)
Array1 [[0 1 2]
 [3 4 5]]

Shape array2 (3,)
Array2 [ 6 10 14]


In [57]:
# Suma de ambos Arrays
array1+array2

array([[ 6, 11, 16],
       [ 9, 14, 19]])

## Funciones estadísticas sobre Arrays

In [59]:
# Creación de un Array unidimensional

array1 = np.arange(1,20,2)
print("array1", array1)


array1 [ 1  3  5  7  9 11 13 15 17 19]


In [60]:
# Media de los elementos del Array
array1.mean()

10.0

In [61]:
# Suma de los elementos del Array
array1.sum()

100

Funciones universales eficientes proporcionadas por numpy: **ufunc**

In [62]:
# Cuadrado de los elementos del Array
np.square(array1)

array([  1,   9,  25,  49,  81, 121, 169, 225, 289, 361])

In [63]:
# Raiz cuadrada de los elementos del Array
np.sqrt(array1)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894])

In [64]:
# Exponencial de los elementos del Array
np.exp(array1)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08])

In [65]:
# log de los elementos del Array
np.log(array1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])